import type { Metadata } from "next";
import { Inter , Just_Another_Hand, Comic_Neue } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers/Providers";
import NavBar from "@/components/core/NavBar";

const justAnotherHand = Just_Another_Hand({
  variable: "--font-just-another-hand",
  subsets: ["latin"],
  weight: ['400'],
  style: 'normal',
});


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],
  style: 'normal',
});

const comic = Comic_Neue({
  variable: "--font-comic-neue",
  subsets: ["latin"],
  weight: ['400', '700', '300'],
  style: 'normal',
});

export const metadata: Metadata = {
  title: "A Guide for Everything",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${comic.variable} ${inter.variable} ${justAnotherHand.variable} ${comic.className} antialiased`}
      >
        <Providers>
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
